import {strict as assert} from 'node:assert';
import {renderToStaticMarkup} from 'react-dom/server';
import {BlitzLibrary,CourseRoute} from '../components/blitz/library';
import {Infographic,LessonTheory} from '../components/blitz/lesson-theory';
import {teachingSchema,teachingExample} from '../lib/teaching';
import {courseStats,type LearningState,type Course} from '../lib/types';
const chart={kind:'bar_chart' as const,title:'Библиотеки — учебный пример',unit:'Библиотеки, шт.',yMax:8,step:2,data:[{label:'Северный',value:6}]};
const valid={...teachingExample,sections:[{...teachingExample.sections[0],visual:chart},teachingExample.sections[1]]};
assert(teachingSchema.safeParse(valid).success);
assert(teachingSchema.safeParse({...valid,sections:[valid.sections[0],{...valid.sections[1],visual:undefined}]}).success);
assert(!teachingSchema.safeParse({...valid,sections:valid.sections.map(s=>({...s,visual:undefined}))}).success);
for(const visual of [{...chart,step:0},{...chart,yMax:4},{...chart,step:.1},{kind:'data_table',title:'Таблица',columns:['А','Б'],rows:[['1','2','3']]}])assert(!teachingSchema.safeParse({...valid,sections:[{...valid.sections[0],visual},valid.sections[1]]}).success);
const html=renderToStaticMarkup(<Infographic visual={chart} onExpand={()=>{}}/>);assert(html.includes('<svg'));assert(html.includes('height="157.5"'));assert(html.includes('Северный: 6'));assert(html.includes('aria-pressed="true"'));
const lesson={id:'l',title:'Читаем графики',ready:true,teaching:teachingSchema.parse(valid),theory:'Текст',code:'Обычное условие',codeOutput:'6 библиотек',flow:[],flashcard:{front:'Вопрос',back:'Ответ'},questions:[{key:'q0',prompt:'1'},{key:'q1',prompt:'2'},{key:'output',prompt:'3'}]};
const course:Course={id:'c',title:'Математика',source:'Личный маршрут',levels:[{id:'a',title:'Графики',subtitle:'Базовый навык',project:{title:'Мой график',task:'Задача',criteria:[]},lessons:[lesson]}]};
const state:LearningState={courses:[],attempts:[],projects:[],signedIn:true,aiReady:true};
const empty=renderToStaticMarkup(<BlitzLibrary state={state} onCreate={()=>{}} onChoose={()=>{}}/>);assert(empty.includes('Создать блиц'));assert(!empty.includes('tile-progress'));
state.courses=[course];assert.equal(courseStats(state,course).percent,0);
for(const q of lesson.questions)state.attempts.push({id:q.key,course_id:'c',lesson_id:'l',question_key:q.key,correct:1,resolved:0} as any);
assert.equal(courseStats(state,course).percent,100);
const library=renderToStaticMarkup(<BlitzLibrary state={state} onCreate={()=>{}} onChoose={()=>{}}/>);assert(library.includes('aria-valuenow="100"'));assert(!library.includes('Карта обучения'));
const route=renderToStaticMarkup(<CourseRoute course={course} state={state} onBack={()=>{}} onLesson={()=>{}} onProject={()=>{}} onPublish={()=>{}}/>);assert(route.includes('Все мои блицы'));assert(route.includes('Пройден'));
const theory=renderToStaticMarkup(<LessonTheory lesson={lesson} onPractice={()=>{}} onExplain={()=>{}} onExpand={()=>{}}/>);assert(theory.includes('textbook-example'));assert(!theory.includes('<pre>'));
console.log('PASS: chart scale validation, numeric SVG geometry, empty library, earned progress, separate route, prose example rendering');
