import {env} from "cloudflare:workers";
import {getChatGPTUser} from "@/app/chatgpt-auth";
import {builtin,publicCourse,type FullCourse} from "./course";
export class AppError extends Error{constructor(message:string,public status=400){super(message);}}
export function db(){if(!env.DB)throw new AppError("Хранилище временно недоступно. Попробуй ещё раз.",503);return env.DB;}
export async function owner(){const u=await getChatGPTUser();if(!u)throw new AppError("Войди, чтобы сохранить учебный прогресс.",401);return u.userId;}
export function aiReady(){return Boolean((env as any).OPENAI_API_KEY);}
export async function getCourse(id:string,user:string):Promise<FullCourse>{if(id==="python")return builtin;const row=await db().prepare("SELECT data FROM courses WHERE id = ? AND owner = ?").bind(id,user).first<{data:string}>();if(!row)throw new AppError("Блиц не найден.",404);return JSON.parse(row.data);}
export async function state(user:string){const d=db();const [c,a,p]=await Promise.all([d.prepare("SELECT data FROM courses WHERE owner = ? ORDER BY created_at DESC").bind(user).all<{data:string}>(),d.prepare("SELECT id,course_id,lesson_id,question_key,answer,correct,resolved,snapshot,remediate_for,created_at FROM attempts WHERE owner = ? ORDER BY created_at ASC").bind(user).all(),d.prepare("SELECT id,course_id,level_id,body,status,feedback,created_at FROM projects WHERE owner = ?").bind(user).all()]);return {courses:[publicCourse(builtin),...c.results.map(x=>publicCourse(JSON.parse(x.data)))],attempts:a.results.map((a:any)=>{if(a.question_key!=="transfer"||a.correct)return a;const snapshot=JSON.parse(a.snapshot);return {...a,snapshot:JSON.stringify({...snapshot,correctAnswer:"",explanation:"Повтори правило и попробуй решить пример самостоятельно."})};}),projects:p.results,aiReady:aiReady(),signedIn:true};}
export async function model(user:string,instructions:string,input:string,json=false,maxTokens=3500){const key=(env as any).OPENAI_API_KEY;if(!key)throw new AppError("Astra ещё не подключена. Готовый курс и разборы доступны; для генерации и чата нужен ключ OpenAI в настройках сайта.",503);const usageId=`${user}:${new Date().toISOString().slice(0,10)}`;const used=await db().prepare("INSERT INTO ai_usage(id,count) VALUES(?,1) ON CONFLICT(id) DO UPDATE SET count=count+1 WHERE count<60 RETURNING count").bind(usageId).first();if(!used)throw new AppError("Дневной лимит ИИ-запросов достигнут. Продолжи завтра.",429);let response;try{response=await fetch("https://api.openai.com/v1/responses",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${key}`},body:JSON.stringify({model:(env as any).OPENAI_MODEL||"gpt-6-astra",instructions,input,reasoning:{effort:"low"},max_output_tokens:maxTokens,store:false,...(json?{text:{format:{type:"json_object"}}}:{})}),signal:AbortSignal.timeout(maxTokens>10000?240000:90000)});}catch{throw new AppError("Astra не ответила вовремя. Твой ответ сохранён в поле — попробуй ещё раз.",504);}if(!response.ok){const problem:any=await response.json().catch(()=>({}));const code=problem?.error?.code;const type=problem?.error?.type;if(code==="credit_balance_exhausted"||type==="insufficient_quota"||code==="insufficient_quota")throw new AppError("На балансе OpenAI API закончились средства или достигнут лимит расходов. Пополни баланс API или проверь лимиты проекта. Твои материалы и прогресс сохранены.",402);if(response.status===401)throw new AppError("Ключ Astra недействителен. Проверь подключение в настройках сайта.",502);if(response.status===403||code==="model_not_found")throw new AppError("У выбранного проекта нет доступа к Astra. Проверь доступ к модели в OpenAI.",502);throw new AppError(response.status===429?"Слишком много запросов к Astra. Подожди немного и попробуй снова.":"Astra временно недоступна. Попробуй позже.",502);}const data:any=await response.json();if(data.status!=="completed")throw new AppError("Astra не закончила ответ. Попробуй ещё раз.",502);const text=data.output?.flatMap((o:any)=>o.content||[]).filter((c:any)=>c.type==="output_text").map((c:any)=>c.text).join("\n");if(!text)throw new AppError("Astra вернула пустой ответ. Попробуй ещё раз.",502);return text;}
