"use client";
import {ArrowRight,Check,Lightbulb,Sparkles,Target,Expand} from "lucide-react";
import type {Lesson} from "@/lib/types";
import type {LessonVisual} from "@/lib/teaching";
import {TheoryMarkdown} from "./theory-markdown";
import {SubjectVisual} from "./subject-visual";

function More({label,onClick}:{label:string;onClick:(focus:string)=>void}){return <button type="button" className="theory-more" aria-label={`Подробнее: ${label}`} onClick={()=>onClick(label)}><Expand size={13}/>Подробнее</button>;}
function Example({text,label,prose=false,onExpand}:{text:string;label:string;prose?:boolean;onExpand:(focus:string)=>void}){if(!text)return null;return prose?<div className="textbook-example"><span>{label}</span><p>{text}</p><More label={`${label}: ${text}`} onClick={onExpand}/></div>:<div className="code-block"><div>{label}</div><pre><code>{text}</code></pre><More label={`${label}: ${text}`} onClick={onExpand}/></div>;}
export function Infographic({visual,onExpand}:{visual:LessonVisual;onExpand?: (focus:string)=>void}){return <><figure className={`learning-visual visual-${visual.kind}`}><figcaption>{visual.title}</figcaption><SubjectVisual visual={visual}/>{visual.kind==="flow"&&<ol className="visual-flow">{visual.items.map((item,i)=><li key={i}><span className="visual-step-number">{i+1}</span><strong>{item.label}</strong><p>{item.detail}</p>{i<visual.items.length-1&&<ArrowRight className="visual-arrow" size={18} aria-hidden="true"/>}</li>)}</ol>}{visual.kind==="compare"&&<div className="visual-table-scroll"><table><thead><tr><th scope="col">Сравним</th><th scope="col">{visual.left}</th><th scope="col">{visual.right}</th></tr></thead><tbody>{visual.rows.map((row,i)=><tr key={i}><th scope="row">{row.aspect}</th><td>{row.left}</td><td>{row.right}</td></tr>)}</tbody></table></div>}{visual.kind==="map"&&<div className="visual-map"><div className="map-center">{visual.center}</div><ul>{visual.items.map((item,i)=><li key={i}><span className="map-dot" aria-hidden="true"/><strong>{item.label}</strong><p>{item.detail}</p></li>)}</ul></div>}{visual.kind==="layers"&&<ol className="visual-layers">{visual.items.map((item,i)=><li key={i} style={{marginLeft:`${i*12}px`}}><span>{String(i+1).padStart(2,"0")}</span><div><strong>{item.label}</strong><p>{item.detail}</p></div></li>)}</ol>}</figure>{onExpand&&<More label={`Иллюстрация «${visual.title}»`} onClick={onExpand}/>}</>;}

export function LessonTheory({lesson,onPractice,onExplain,onExpand}:{lesson:Lesson;onPractice:()=>void;onExplain:()=>void;onExpand:(focus:string)=>void}){
 const teaching=lesson.teaching;
 if(teaching?.version===3)return <div className="lesson-copy structured-theory"><TheoryMarkdown theory={teaching} onExpand={onExpand} renderVisual={v=><Infographic visual={v}/>}/><div className="lesson-actions"><button className="button primary" onClick={onPractice}>К практике <ArrowRight size={18}/></button><button className="button outline" onClick={onExplain}><Sparkles size={17}/>Спросить наставника</button></div></div>;
 return <div className="lesson-copy structured-theory">{teaching?<>
  <header className="theory-intro"><span className="card-kicker">ТЕОРИЯ · ПОШАГОВО</span><h2>{teaching.goal}</h2><p>{teaching.why}</p><More label={`Цель урока: ${teaching.goal}. ${teaching.why}`} onClick={onExpand}/></header>
  <section className="theory-foundations"><h3>Главное перед началом</h3><dl>{teaching.foundations.map((item,i)=><div key={i}><dt>{item.term}</dt><dd>{item.meaning}</dd><More label={`${item.term}: ${item.meaning}`} onClick={onExpand}/></div>)}</dl></section>
  {teaching.sections.map((section,i)=><section className="theory-section" key={i}><h3>{section.title}</h3><More label={`Разъясни раздел «${section.title}»`} onClick={onExpand}/><div className="theory-paragraph">{section.body.split(/\n\s*\n/).map((paragraph,j)=><div className="theory-fragment" key={j}><p>{paragraph}</p><More label={`${section.title}: ${paragraph}`} onClick={onExpand}/></div>)}</div>{section.visual&&<Infographic visual={section.visual} onExpand={onExpand}/>}<div className="visual-takeaway"><Lightbulb size={16} aria-hidden="true"/><span>{section.takeaway}</span><More label={`Вывод: ${section.takeaway}`} onClick={onExpand}/></div></section>)}
  <section className="theory-example"><h3>Пример</h3><More label="Покажи, как разобрать пример из этого урока" onClick={onExpand}/><Example text={lesson.code} label="Условие" prose={teaching.exampleFormat==="prose"} onExpand={onExpand}/><ol className="example-walkthrough">{teaching.exampleSteps.map((step,i)=><li key={i}><p>{step}</p><More label={`Шаг ${i+1}: ${step}`} onClick={onExpand}/></li>)}</ol><Example text={lesson.codeOutput} label="Полученный результат" prose={teaching.exampleFormat==="prose"} onExpand={onExpand}/></section>
  <aside className="theory-pitfall"><div><h3>Где легко ошибиться</h3><p>{teaching.pitfall.mistake}</p><More label={`Типичная ошибка: ${teaching.pitfall.mistake}`} onClick={onExpand}/><p><strong>Как разобраться: </strong>{teaching.pitfall.correction}</p><More label={`Как исправить: ${teaching.pitfall.correction}`} onClick={onExpand}/></div></aside>
  <section className="theory-check"><div className="card-kicker">ПРОВЕРЬ СЕБЯ</div><h3>{teaching.check.prompt}</h3><More label={`Вопрос для самопроверки: ${teaching.check.prompt}`} onClick={onExpand}/><details><summary>Подсказка</summary><p>{teaching.check.hint}</p><More label={`Подсказка: ${teaching.check.hint}`} onClick={onExpand}/></details><details><summary>Показать рассуждение</summary><p>{teaching.check.answer}</p><More label={`Разбор ответа: ${teaching.check.answer}`} onClick={onExpand}/></details></section>
  <section className="theory-recap"><h3>Главное</h3><ul>{teaching.recap.map((item,i)=><li key={i}><span>{item}</span><More label={`Главное: ${item}`} onClick={onExpand}/></li>)}</ul></section>
 </>:<><h2>{lesson.title}</h2><div className="theory-fragment"><p>{lesson.theory}</p><More label={lesson.theory} onClick={onExpand}/></div><div className="flow-diagram">{lesson.flow.map((text,i)=><div key={i}><span className="flow-step"><small>0{i+1}</small><strong>{text}</strong></span>{i<lesson.flow.length-1&&<ArrowRight size={20}/>}</div>)}</div><Example text={lesson.code} label="Пример" onExpand={onExpand}/><Example text={lesson.codeOutput} label="Результат" onExpand={onExpand}/></>}
  <div className="lesson-actions"><button className="button primary" onClick={onPractice}>К практике <ArrowRight size={18}/></button><button className="button outline" onClick={onExplain}><Sparkles size={17}/>Спросить наставника</button></div>
 </div>;
}
